### ISSUE TITLE
Add number of times answer was wrongly guessed in FinishPanel.

### ISSUE THREAD

**Issue by duckifyz** [duckifyz/vtp5#16]
This will just be tedious and relies on a commit I haven't pushed yet. Also, this is not needed whatsoever but is a good feature to have.

**Comment by abdelabdalla** [comment]
Bump

**Comment by duckifyz** [comment]
Doing it right now.

**Comment by leMingathon** [comment]
It has been revived! Can the user **sort** the words based on number of times answered incorrectly?

**Comment by duckifyz** [comment]
I'm working on that but the fact that a new FinishPanel object isn't created everytime is making it far too difficult. I'll work on it at school sometime.

**Comment by duckifyz** [comment]
I'm closing this issue and creating a separate one.
