### ISSUE TITLE
Have a panel for inputting special characters

### ISSUE THREAD

**Issue by abdelabdalla** [duckifyz/vtp5#26]
This is for letters with things such as accents which cannot be typed by a UK keyboard

**Comment by leMingathon** [comment]
There's probably an open-source international keyboard we can use.

**Comment by leMingathon** [comment]
Links which may be useful:
http://sourceforge.net/projects/virtualkey/ [MOST PROMISING]
http://jvkeyboard.sourceforge.net/ [Maybe...]

**Comment by leMingathon** [comment]
Done!
