### ISSUE TITLE
Ability to import multiple files

### ISSUE THREAD

**Issue by abdelabdalla** [duckifyz/vtp5#27]
EDIT: This would combine multiple text files into one test.

**Comment by leMingathon** [comment]
As in a "Combine" feature?

**Comment by abdelabdalla** [comment]
Exactly that

**Comment by duckifyz** [comment]
That wouldn't be too hard to implement.

**Comment by abdelabdalla** [comment]
We have decided to let the user select multiple files when choosing txt files

**Comment by leMingathon** [comment]
Should be fine now.
