### ISSUE TITLE
Clean up files that VTP5 uses.

### ISSUE THREAD

**Issue by leMingathon** [duckifyz/vtp5#28]
Currently, there are a lot of files (especially in the MigLayout and Jazzy libraries) that VTP5 doesn't actually use. Removing these files will reduce the size of VTP5.

**Comment by leMingathon** [comment]
Just MigLayout that needs to be cleaned up now.

**Comment by duckifyz** [comment]
MigLayout and GitHub have been cleaned as much as I could without actually going into the jars and handpicking the classes we want and so I'm closing this issue FOR NOW.
