### ISSUE TITLE
Colour schemes?

### ISSUE THREAD

**Issue by leMingathon** [duckifyz/VTP5#29]

**Comment by abdelabdalla** [comment]
I have 3 colour schemes based around the three main colours of the logos. Will post rgb values as soon as I can

**Comment by duckifyz** [comment]
I don't like the idea of colour schemes. This is still a vocab testing program after all, not a game. Maybe be able to change the background colour, but I don't think we should do anymore than that

**Comment by duckifyz** [comment]
Woops.

**Comment by leMingathon** [comment]
Fair enough, that's probably a better idea. They can already change the button colour and text colour - we basically just need background colour and we're pretty much done.
