### ISSUE TITLE
Make the stats section more user-friendly

### ISSUE THREAD

**Issue by leMingathon** [duckifyz/vtp5#30]
We'll need to wait for more feedback though.

- Luke Meyer suggested just having words left (and maybe either total guesses or success rate or both).

**Comment by duckifyz** [comment]
This is a good idea. I think we should definitely have success rate and words left, and I'm not sure about total # of guesses.

**Comment by leMingathon** [comment]
Hmm... TBH total # of guesses isn't that useful. Also, LM suggested having a sort of "graphic" rather than a list - maybe use paintComponent to draw the strings?

**Comment by duckifyz** [comment]
What kind of graphic would it be though?

**Comment by leMingathon** [comment]
We could try doing a mockup... I'll have a go when I have time.

**Comment by duckifyz** [comment]
I've removed the first two stats. This may be temporary, but everyone agreed that this complicated the stats area. I may create another issue  about improving this.
