### ISSUE TITLE
Change look and feel and make it compatible.

### ISSUE THREAD

**Issue by duckifyz** [duckifyz/vtp5#38]

**Comment by leMingathon** [comment]
???

**Comment by abdelabdalla** [comment]
Would be possible to only change the look of the file chooser and popups. We don't need to change the buttons

**Comment by duckifyz** [comment]
I've done a bit of research and I've found out that you cannot selectively apply look and feels and the reason that the Windows look and feel had white buttons is because Windows buttons do not have the capability for backgrounds. My idea therefore is to have a theme selector. If the user chooses the defaults (the one we have now), then the settings will stay the same, but if the user chooses the system look and feel and the user is on windows, the button colour option will be disabled. I'm creating issue #54 for this.

**Also, this could be the reason for issue #47 as well. If Ming could do a bit of research to find out if this is true.**

For now though, I'm closing this issue.

**Comment by leMingathon** [comment]
Current look and feel is pretty good, just a couple of things:
- Alignment (especially of some text and Switch Language checkbox) is a bit dodgy
- Button colour changing needs to be modified to make it work correctly
